### PR TITLE
explain the proof structure.

### PR DESCRIPTION
**Pull request by jackzhp**
I really think this is needed.

### CODE REVIEW

**Comment by apoelstra** [comment]
The rangeproof module has nothing to do with Bulletproofs.

**Comment by apoelstra** [comment]
Out of curiosity, what are you doing with these rangeproofs from this module?

**Comment by jackzhp** [comment]
@apoelstra  I have no idea. I am trying to understand the code. really appreciated that you told me rangeproof module has nothing to do with the bulletproofs.

**Comment by jackzhp** [comment]
@apoelstra  by the way, I thought grin is using it to prove value are in the right range, isn't it? grin is written in rust, and eventually call into this(I thought, but I am not sure).

**Comment by apoelstra** [comment]
No, grin has never used this module.

**Comment by jackzhp** [comment]
you did not tell, but with your information, eventually, I found it: https://github.com/mimblewimble/secp256k1-zkp 

thanks for your information.

**Comment by apoelstra** [comment]
Closing as out of date

**Pull request closed without merging**
