### PR TITLE
Update macOS image for CI

### PR DESCRIPTION
**Pull request by sanket1729**

### CODE REVIEW

**Comment by real-or-random** [comment]
Are we okay with backporting a single commit without our script? Just checking, I guess there's no real reason not to do it, but we never did, so I'm not entirely sure.

**Comment by sanket1729** [comment]
No strong opinions. The decision is best taken by the maintainers here. It was requested by @apoelstra https://github.com/ElementsProject/secp256k1-zkp/pull/205#issuecomment-1398410574

**Comment by real-or-random** [comment]
Yep, I saw, my question was more towards the maintainers. :) 

Maybe we should at least use the script in "single-commit" mode (https://github.com/ElementsProject/secp256k1-zkp/blob/master/contrib/sync-upstream.sh#L10). @sanket1729 Would you be willing to try that?

**Comment by sanket1729** [comment]
Nevermind, I have to pass it a merge commit. Will try again

**Comment by sanket1729** [comment]
Still failing if I pass the corresponding merge commit to the script.


```
./contrib/sync-upstream.sh select 751c4354d51fb5b10a80764df627b84e1a5ccd4f
-----------------------------------
Upstream PRs 1152
-----------------------------------

[bitcoin-core/secp256k1#1152]: Update macOS image for CI

This PR can be recreated  with `./contrib/sync-upstream.sh 751c4354d51fb5b10a80764df627b84e1a5ccd4f`.
-----------------------------------
M	contrib/sync-upstream.sh
Already on 'master'
Your branch is ahead of 'origin/master' by 486 commits.
  (use "git push" to publish your local commits)
Already up to date.
fatal: 'temp-merge-$   ' is not a valid branch name.
```

**Comment by sanket1729** [comment]
Actually, this was something on my end. But selecting that single commit results in some conflicts that I am not sure how to resolve.

**Review by real-or-random — APPROVED** [review]
utACK 3b2c675955874a077482f6c8983970194fcbc3ed

**Review by jonasnick — COMMENTED** [review]
ACK 3b2c675955874a077482f6c8983970194fcbc3ed

**Pull request merged**
