### PR TITLE
Changes necessary for usage on Trezor

### PR DESCRIPTION
**Pull request by real-or-random**
This is the result from cherry-picking the following upstream PRs (in this order) in their current state, see the PRs for details:
 * https://github.com/bitcoin-core/secp256k1/pull/566
 * https://github.com/bitcoin-core/secp256k1/pull/595
 * https://github.com/bitcoin-core/secp256k1/pull/596
 * https://github.com/bitcoin-core/secp256k1/pull/533
 * https://github.com/bitcoin-core/secp256k1/pull/587

cc @practicalswift: The reason I asked you to update https://github.com/bitcoin-core/secp256k1/pull/587 is that I needed the change here. Sorry, I didn't mention this, I hope you don't mind. :)

### CODE REVIEW

**Comment by real-or-random** [comment]
Forced pushed because I forgot to cherry-pick the (cosmetic) 76c7964 from  bitcoin-core/secp256k1#596, and I also added a zkp-specific follow-up commit on this commit.

**Comment by apoelstra** [comment]
Also missing `8558e3d` from https://github.com/bitcoin-core/secp256k1/pull/595

**Comment by apoelstra** [comment]
Would be good to add `ARG_CHECK_NO_RETURN(ctx != secp256k1_context_no_precomp);` to `secp256k1_cotnext_destroy` as well as `secp256k1_prealloc_destroy` when cherry-picking `2ca27e2` from https://github.com/bitcoin-core/secp256k1/pull/595

I also have a bunch of spacing changes in `a6add6c`, also from https://github.com/bitcoin-core/secp256k1/pull/595, that you don't have. I think in this case I screwed up the cherry-pick and created a bigger diff than I needed to.

**Comment by real-or-random** [comment]
> Would be good to add `ARG_CHECK_NO_RETURN(ctx != secp256k1_context_no_precomp);` to `secp256k1_cotnext_destroy` as well as `secp256k1_prealloc_destroy` when cherry-picking `2ca27e2` from [bitcoin-core/secp256k1#595](https://github.com/bitcoin-core/secp256k1/pull/595)

This check is actually present in the current PR in `secp256k1_preallocated_destroy` (and `secp256k1_context_destroy` is also covered because it calls `secp256k1_preallocated_destroy` internally).

I'm addressing the other issues.

**Comment by real-or-random** [comment]
I added 8558e3d and a fixup from bitcoin-core/secp256k1#596, both just on top. I didn't squash or reorder to make sure you don't have to recreate it again from scratch. Let me know when I should squash.

**Comment by apoelstra** [comment]
ACK. Go ahead and squash.

**Comment by real-or-random** [comment]
done

**Comment by apoelstra** [comment]
ACK

**Pull request merged**
