### PR TITLE
Update Schnorrsig and MuSig

### PR DESCRIPTION
**Pull request by jonasnick**
The current schnorrsig and musig module are not compatible with bip-schnorr anymore. This PR cherry-picks the following commits from https://github.com/bitcoin-core/secp256k1/pull/558:
```
84308855d6e6562bd8d52677f681ab68735d3467 f remove nonce_is_negated parameter
639a8599ec97121970566c3a1f9e6fb763471c83 f use tagged hashes in nonce derivation and signature hash
2e76c5dc6d6ff4e30aac481820648ae95353abcf f don't allow counter != 0 in nonce function
7eeb3aa49832015a8aa8caf17a008d263f373fc0 f add xonly pubkey struct which is serialized as 32 byte and whose Y coordinate is a quadratic residue
add8e78542e29c3aab0d462425a4988689cdb331 f use xonly_pubkeys in schnorrsig sign and verify
2e4ed392e1fd8cb7c64787bde9b67ddc0b463e3d f add tweak functions for xonly_pubkeys
84fe42737d9f915a53e3e682ebd11021e24bfd52 f address some of pieter's comments
e28b61c290f4549dfeb94b421310ff68b661fea0 f const casting
5764b2b2b7e9d96c7704364e55c17ed064217398 f test that pubkey is zeroed after xonly_pubkey_parse returned 0
74bb3b4318b4c17b8cb01fa9d42ee776094b1743 f don't use secp256k1_pubkeys in xonly_tweak api and instead use is_positive flag
dfce048bdec171fa76384a28136c59acd80f9b5a f remove xonly_pubkey_to_pubkey
2b36bf7db30d399878f8b32abf3fe29039f79809 f sign -> is_positive
26f95c556a088dc9e83e587d96534429a1974737 f feed seckey that is actually signed with (i.e. perhaps negated) into nonce functions
538052c95039e84c2f6b2790b826b86765f8d2c3 f reenable test vectors
b5fcf541495d78595c0bcbecdba58219a866b7f3 f uninitialized memory in tests
affa6e87e972b7d2f48a60b79b9360f8b15db021 f rename is_positive in xonly_pubkey api to has_square_y
44881b21e3876fd63a4674fdc1375709e31cd694 f rename is_positive in schnorrsig module to has_square_y
9d5373307cfad5fa1b53820d417a8155d2d557dc f add new bip-schnorr test vector 14
a87a0576dcc7188f8babc3fc9ec5f2a68522ff6d f Move most of ec_pubkey_absolute into ge_absolute to make it available to functions which don't operate on pubkeys but on group elements.
7dbb2e8f9bc942c0d1ae5efdcbf9e9636c975be3 f add macro SECP256K1_LEN_XONLY_PUBKEY equal to 32 to allow reducing magic numbers in calling code
19c144cccac293a1814cef36db198b176d237072 f rename schnorrsig_real_verify because it doesn't verify
4a81b4ac88e917f87c4bcf1f002bfa2671fd895e f don't use ec_pubkey_parse indirection in xonly_pubkey_parse
93dc57ad0b6c60be773621734af9fbcb78c5bfd0 f don't use ec_pubkey_parse indirection in xonly_pubkey_parse
b3b1a204f6d4b403b4d9b53d622c0348a35b811c f rename xonly_pubkey_tweak_verify to xonly_pubkey_tweak_test and add a few notes that this does not verify anything cryptographically
f76092bad771505b882f799547670a8979786e80 f pubkey_tweak_verify -> pubkey_tweak_test in secp256k1.h
ed442f6f6c44bcf8de21932a76ad4566da30e52b f add secp256k1_xonly_pubkey_load and secp256k1_xonly_pubkey_save to avoid casting (especially accidentally casting const away)
ae143ddbbebeb243b4ea89ced5bb1fd740dada78 f remove unnecessary schnorrsig_verify_helper, check for return values of pubkey_serialize, and add tests for zeroized pubkeys in schnorrsig_verify and schnorrsig_verify_batch
e7d599c77c188931d29707e28f0c38297a8f12de f maximize branch coverage in schnorrsig module
b58720789f0a3abe8ffa91f9ddc07908ea4b6c89 f full branch coverage in xonly_pubkey functions
9f9a918cacf6bd3c9abf292d53a4d6d4ec498d25 f rename has_square_y to is_negated
2579495e9f8b798e767eed262dfc2dd338e3c9c4 f rename has_square_y to is_negated
84e748d3446f0446793de8157506b5faed3ee241 f tweak_test doc
192f9c593cc5697c4278dbb13e5f7a330ad951d8 f address tim's xonly comments
e806b4e39c926c2647528eca8ed32020deea126e f address tim's schnorrsig comments
2b13861de8a8e2f3c02502d0b17f3b90c4bc60ba f unused argument warning (VERIFY_CHECK is side effect safe)
f3aaf4faa76a8e6f10b6cc7388e60cd49a981e1a f remove unnecessary normalize in xonly
cfcaf2f823d14a3e12a69f9eab715d8b72fa3b54 f remove unnecessary normalize in schnorrsig
```
The files in `src/modules/schnorrsig/` should be identical to the ones in the upstream PR.

As for the MuSig updates see the commit message:
```
Fix the MuSig module after integrating bip-schnorr updates
    1.  using xonly_pubkeys in MuSig for input public keys and the combined
        pk. For that to work we need to store whether the MuSig aggregated point
        has a square y in the session, may need to negate each signers secret
        key and may need to negate each signers public key in
        musig_partial_sig_verify.
    2.  using a tagged hash for the message hash.
    
    The tweak_test is removed because this doesn't work anymore.
```

Note that adaptors are still normal pubkeys and not xonly (not sure what's better). I thought about adding some of the rationale to the musig.md, but that one doesn't even explain the need to negate the nonce (yet). Instead, I added comments about what happens to the code. I think we should have a followup PR that renames `nonce_is_negated` to `nonce_has_square_y` (which is more established now) and change the type of public nonces either to a new nonce type or xonly_pubkeys.

EDIT: ~~Also we'll need a follow up PR to allow adding taproot tweaks to musig combined keys again. The method we've used previously (just use ec_tweak_add on the combined public key) doesn't work with xonly pubkeys. We'll need to specify the tweak in pubkey_combine and carry it over to the session.~~ (EDIT: Added a commit with tweaking)

EDIT 2: Just fyi, we need an additional scalar mult in session_initialize that we previously didn't need in order to figure out if the signer's public key point has a square Y.

### CODE REVIEW

**Comment by jonasnick** [comment]
Force pushed with a squashed commit that introduces a `pre_session` struct instead of a byte array to pass information from `pubkey_combine` into the session. This paves the way for adding tweaks again.

**Comment by jonasnick** [comment]
I grabbed a few new fixups from upstream schnorrsig and added a commit to reintroduce tweaking.

**Comment by jonasnick** [comment]
I cherry-picked more fixup commits from the upstream PR and squashed. The easiest way to review this PR is to compare the files with the upstream PR files. They should match (mostly).
```
vimdiff ./src/modules/schnorrsig/main_impl.h ../secp256k1/src/modules/schnorrsig/main_impl.h 
vimdiff ./src/modules/schnorrsig/tests.h ../secp256k1/src/modules/schnorrsig/tests.h        
vimdiff ./src/modules/schnorrsig/tests_impl.h ../secp256k1/src/modules/schnorrsig/tests_impl.h
vimdiff ./src/secp256k1.c ../secp256k1/src/secp256k1.c 
vimdiff ./include/secp256k1.h ../secp256k1/include/secp256k1.h 
vimdiff ./include/secp256k1_schnorrsig.h ../secp256k1/include/secp256k1_schnorrsig.h
```

**Comment by pinheadmz** [comment]
Hey, just curious... where are these commits from originally? For example

```
84308855d6e6562bd8d52677f681ab68735d3467 f remove nonce_is_negated parameter
```

I don't see that in bitcoin-core/secp256k1 

Thanks, just trying to follow schnorr integration in both repos...

**Comment by jonasnick** [comment]
@pinheadmz I squashed the fixups both here and upstream to simplify review. You can find them in this branch: https://github.com/jonasnick/secp256k1-zkp/tree/schnorrsig-updates-backup5

**Comment by jonasnick** [comment]
Updated with upstream fix `6e0290679cea29c5671574f378cb8377e51ad79f f is_negated and added test`

**Comment by jonasnick** [comment]
Replaced by #92

**Pull request closed without merging**
