### PR TITLE
Remove unused context initializer functions

### LINKED ISSUE #15: Context initializers
I found that functions `secp256k1_pedersen_context_initialize` and `secp256k1_rangeproof_context_initialize` declared in `/include/secp256k1_rangeproof.h` have no implementations. 
Is it true, that it is unnecessary to additionaly initialize context?

### PR DESCRIPTION
**Pull request by thomaseizinger**
Fixes #15.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
lol. now that we've stopped rebasing maybe these will stay gone :)

**Comment by thomaseizinger** [comment]
> lol. now that we've stopped rebasing maybe these will stay gone :)

I wasn't aware! Did functions keep coming back from upstream?

**Comment by apoelstra** [comment]
These functions existed a *very* long time ago, in Elements Alpha, before Elements had Confidential Asset support. @sipa and I spent some time in 2016 replacing the precomputation tables in the rangeproof code with non-precomp code, since our constant `H` generator was replaced by a variable asset generator as part of CA. But we forgot to remove the two precomputation functions from the header.

We noticed this some years later, and I swear I remember deleting them after that, but at some point a few rebases had gone by and I saw that they'd returned. This may have happened more than once, I don't remember now.

I deleted them again as part of #108 but you beat me to it :)

**Comment by apoelstra** [comment]
lol, I realize that the rangeproof sign/verify functions still talk about needing a context "initialized for rangeproof and pedersen commitment"

**Pull request merged**
