### PR TITLE
[upstream PR #773]: Fix some compile problems on weird/old compilers.

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by apoelstra** [comment]
Generated this PR automatically by looking at the list of merged PRs upstream and creating new PRs (from the same commit) here.

**Comment by real-or-random** [comment]
@apoelstra What's the plan here? Is this just a test for your scripts? Or should we review this?

**Comment by apoelstra** [comment]
@real-or-random both. If we can merge this I can do a series of these PRs, until we hit a merge conflict, then we can decide on a process for how to deal with that.

My proposal here is that we start continuously merging PRs from upstream into libsecp-zkp, rather than rebasing (and rather than doing the subtree-based schemed that @jonasnick has been experimenting with).

**Review by jonasnick — APPROVED** [review]
ACK 1309c03c45beece646a7d21fdb6a0e3d38adee2b

**Pull request merged**
