### PR TITLE
ecdsa_s2c: rename anti-klepto to anti-exfil

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Review by real-or-random — APPROVED** [review]
ACK e354c5751d670716791778d86c1dcd599f2e1a9c diff looks good, I haven't checked that no occurrence is missed

**Comment by apoelstra** [comment]
you can just `git grep -i klepto` and see it doesn't appear

**Comment by benma** [comment]
The commit message is unfortunately empty. Just curious, what was the reason for the change? Noticing it now since I am updating to a newer version of this lib.

**Comment by apoelstra** [comment]
Blockstream marketirng saying that "kleptography" is not a widely understood term.

**Pull request merged**
