### PR TITLE
Upstream PRs  #854 #852 #857 #858 #860 #845 #862 #875 #878 #874 #877 #880 #864 #882 #894 #891 #901

### PR DESCRIPTION
**Pull request by jonasnick**
[upstream PR #854]: Rename msg32 to msghash32 in ecdsa_sign/verify and add explanation
[upstream PR #852]: Add sage script for generating scalar_split_lambda constants
[upstream PR #857]: docs: fix simple typo, dependecy -> dependency
[upstream PR #858]: Fix insecure links
[upstream PR #860]: fixed trivial typo
[upstream PR #845]: Extract the secret key from a keypair
[upstream PR #862]: Autoconf improvements
[upstream PR #875]: Avoid casting (void**) values.
[upstream PR #878]: Remove unused secp256k1_fe_inv_all_var
[upstream PR #874]: Remove underscores from header defs.
[upstream PR #877]: Add missing secp256k1_ge_set_gej_var decl.
[upstream PR #880]: Add parens around ROUND_TO_ALIGN's parameter.
[upstream PR #864]: Add support for Cirrus CI
[upstream PR #882]: Use bit ops instead of int mult for constant-time logic in gej_add_ge
[upstream PR #894]: ctime_test: move context randomization test to the end
[upstream PR #891]: build: Add workaround for automake 1.13 and older
[upstream PR #901]: ci: Switch all Linux builds to Debian and more improvements

This PR was automatically created with `./contrib/sync-upstream.sh `.

Also added -zkp modules to .cirrus.yml - with some small simplifications, but I didn't spend to much time on it because we may refactor this anyway upstream.

### CODE REVIEW

**Comment by real-or-random** [comment]
Still failing:

https://cirrus-ci.com/task/6253397255913472?command=cat_tests_log#L3

**Comment by real-or-random** [comment]
> This PR was automatically created with `./contrib/sync-upstream.sh `.

Shouldn't the script show the entire command? Also see #127. :)

**Comment by jonasnick** [comment]
Yeah that'd be an improvement but it was just `./contrib/sync-upstream.sh range` (which isn't great because it can't be easily reproduced when upstream merges new PRs).

**Comment by real-or-random** [comment]
> Yeah that'd be an improvement but it was just `./contrib/sync-upstream.sh range` (which isn't great because it can't be easily reproduced when upstream merges new PRs).

Yeah I'm adding a commit to my PR. :)

**Comment by real-or-random** [comment]
ACK 4091e619248b4723a2a4ed5dd7289628ee0320a5 merge commit picks the right parents, merge resolution and  additional commit look good

**Pull request merged**
